### ISSUE TITLE
Not compiled with -d:ssl

### ISSUE THREAD

**Issue by ThomasTJdev** [flenniken/nimlist#1]
Hi

A clean nimble install with `nimble install nimlist` results in:

```nim
$ nimlist
Downloading package list...
Error: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable.
Stack at time of error:
httpclient.nim(791)      newConnection
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [HttpRequestError]
```

**Comment by flenniken** [comment]
I pulled your change but it doesn't fix the issue for me.  I also tried adding a switch statement to the build task as shown below, but that doesn't work either.  You need to delete packages.json to test which forces a download.

```
task build, "Build":
  switch("d", "ssl")
```

**Comment by flenniken** [comment]
I added a config.nims file with switch("define", "ssl") and that fixed the issue.
